export const Employees = [
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Payroll Only',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Payroll Only',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Invite Sent',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Invite Sent',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
  {
    id: 'FHA4532',
    profile: 'profile 1',
    email: 'example@gmail.com',
    role: 'Lead Designer',
    status: 'Active',
  },
];
